### ISSUE TITLE
Update `interactive.jl` notebook for new Pluto version

### ISSUE THREAD

**Issue by fonsp** [ClimateMARGO/interactive#1]
- [x] Make sure the `@initially` macro still works
- [x] Save notebook file with new Pluto
- [ ] Dark mode support, this seems to work:
```css
pluto-output img, pluto-output svg {
    filter: invert(1) hue-rotate(180deg) contrast(0.83) brightness(1.4);
}
```
- [x] Update PlutoUI
